<?php

/**
 * @file
 * A custom module for ET that defines blocks, probably for static content.
 * This will make it easier to have things in code.
 */

 



/**
 * Implements hook_block_info().
 */
function datawiki_blocks_block_info() {
  $blocks['datawiki_welcome'] = array(
    'info' => t('Welcome Message'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  $blocks['datawiki_branding_header'] = array(
    'info' => t('Branding Header'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  $blocks['datawiki_branding_footer'] = array(
    'info' => t('Branding Footer'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  $blocks['datawiki_facebook_like'] = array(
    'info' => t('Facebook Like'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  $blocks['datawiki_add_data'] = array(
    'info' => t('Add Data'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function datawiki_blocks_block_view($delta = '') {
  switch ($delta) {
    case 'datawiki_welcome':
      $block['subject'] = '';
      $block['content'] = datawiki_blocks_contents('welcome');
      break;
      
    case 'datawiki_branding_header':
      $block['subject'] = '';
      $block['content'] = datawiki_blocks_contents('branding_header');
      break;
      
    case 'datawiki_branding_footer':
      $block['subject'] = '';
      $block['content'] = datawiki_blocks_contents('branding_footer');
      break;     
      
    case 'datawiki_facebook_like':
      $url = ($_SERVER['SERVER_PORT'] == '443') ? 'https' : 'http';
      $url .= '://';
      $url .= ($_SERVER['HTTP_HOST'] == 'localhost') ? 'localhost.com' : $_SERVER['HTTP_HOST'];
      $url .= $_SERVER['REQUEST_URI'];
      $block['subject'] = '';
      $block['content'] = '<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="' . urlencode($url) . '" send="true" width="200" show_faces="false" font=""></fb:like>';
      break;

    case 'datawiki_add_data':
      $block['subject'] = '';
      $block['content'] = datawiki_blocks_contents('add_data');
      break;
  }
  return $block;
}

/**
 * Block placeholder content
 */
function datawiki_blocks_contents($type) {
  $output = '';
  
  switch ($type) {
    case 'welcome':
      $output .= '<h2>' . t('Find groups by place or topic.') . '</h2>';
      break;
      
    case 'branding_header':
      $output .= '<div id="branding-header"></div>';
      break;
      
    case 'branding_footer':
      $code_for_america = '';
      $output .= '<div id="branding-footer"><img src="' . base_path() . path_to_theme() . '/images/cfa-full-logo.png" /></div>';
      break;
      
    case 'add_data':

      $facebook = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/facebook-icon.png" width="50" />';
      $yahoo = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/yahoo_groups_icon_50x50.png" />';
      $google = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/google-groups-icon.jpg" width="80" />';
      $meetup = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/meetup-icon-small.png" />';
      $mailinglist = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/email-icon.png" width="50"/>';
      $twitter = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/twitter_icon.jpg" width="50"/>';
      $blog = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/blog-icon.jpg" width="50" />';
      $mail = '<img src="' . base_path() . path_to_theme() . '/images/groups_icons/mail-icon.png" width="50"/>';
/*       $ning = '<img src="' . base_path() . path_to_theme() . '/images/cfa-full-logo.png" />'; */


      $links = $facebook . $google . $meetup . $mailinglist . $twitter . $blog . $mail . $yahoo /*. $ning */;
      $output .= '
        <div class="add-data">' .
        '<h3>' . t('We make it easy to find groups in your city.') . '</h3>'
        . '<div class="groups-icons">' . $links . '</div>'
/*           . t('Know a cool group? Why not <a href="/node/add/online-community">Add</a> it?') */
        . '</div>';
      break;
      
  }
  
  return $output;
}