<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function datawiki_group_map_help($path, $arg) {
  switch ($path) {
    case 'datawiki_group_map':
      $explanation = t(
        'Custom features for Data Wiki Group Map.');
      return "<p>$explanation</p>";
  }
}


/**
 * Implementatation of hook_menu().
 */
function datawiki_group_map_menu() {
  $items['map/render/community-group'] = array(
    'title' => 'Map',
    'description' => 'Display a map of Community Groups.',
    'page callback' => 'datawiki_group_map_render',
    'page arguments' => array(t('Map page.')),
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_cron_job_scheduler_info().
 *
 * Compare queue names with key names in feeds_cron_queue_info().
 */
function datawiki_group_map_cron_job_scheduler_info() {
  $info = array();
  $info['datawiki_group_map_import'] = array(
    'queue name' => 'datawiki_group_map_import',
  );
  return $info;
}

/**
 * Implements hook_cron_queue_info().
 */
function datawiki_group_map_cron_queue_info() {
  $queues = array();
  $queues['datawiki_group_map_import'] = array(
    'worker callback' => 'datawiki_group_map_import',
    'time' => 15,
  );
  return $queues;
}

/**
 * Scheduler callback for importing from a source.
 */
function datawiki_group_map_import($job) {
  dsm("saving json");
}


function datawiki_group_map_render($settings) {

  $html_root = drupal_get_path('module', 'datawiki_group_map');
  $html_root_custom = $settings['html_root_custom'];
  $sitename = $settings['sitename'];
  $tagline = $settings['tagline'];
  $page_title = $settings['page_title'];

  // Add special stylesheets.
  drupal_add_css(drupal_get_path('module', 'datawiki_group_map') . '/includes/style/fluid_grid.css', array('group' => CSS_THEME));
  drupal_add_css(drupal_get_path('module', 'datawiki_group_map') . '/includes/style/boilerplate.css', array('group' => CSS_THEME));
  drupal_add_css(drupal_get_path('module', 'datawiki_group_map') . '/includes/js/leaflet/leaflet', array('group' => CSS_THEME));
  drupal_add_css($html_root . '/includes/style/style.css"', array('group' => CSS_THEME));
  drupal_add_css($html_root_custom . '/css/style.css"', array('group' => CSS_THEME));
  
  // Add javascript.
  drupal_add_js($html_root . '/includes/js/jquery-1.5.min.js');
  drupal_add_js($html_root . '/includes/js/leaflet/leaflet.js');
  // @TODO Check jquery conflicts mode.

  /*
    @TODO Add this in.  
    <!--[if lte IE 8]><link rel="stylesheet" href="/<?php print $html_root; ?>/includes/style/leaflet/leaflet.ie.css" /><![endif]-->
  */

  $output = '<div id="map-area" class="grid_9 omega">
    <div id="map" style="height: 600px"><div class="loading">Loading Map</div></div>
    <div id="data"></div>
  </div>

  <div id="popup-content" class="block">
      <div class="content">Click map to see where the groups are</div>
  </div>';
  return $output;
}