<?php

/**
 * Cleanup Taxonomy Terms
 */
 
function taxonomy_cleanup_menu() {  
  $items['admin/config/taxonomy_cleanup'] = array(
    'title' => 'Taxonomy Cleanup',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxonomy_cleanup_edit_form'),
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_LOCAL_ACTION,
  );
  
  $items['admin/config/taxonomy_cleanup/remove_empty_terms'] = array(
    'title' => 'Remove Empty Terms',
    'page callback' => 'taxonomy_cleanup_remove_empty_terms',
    'page arguments' => array(),
    'access callback' => TRUE,
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_NORMAL_ITEM,
    'weight' =>  -10,
  );
 
  $items['admin/config/taxonomy_cleanup/merge_similar_terms'] = array(
    'title' => 'Merge Similar Terms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxonomy_cleanup_merge_similar_terms_settings_form'),
    'access callback' => TRUE,
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_NORMAL_ITEM,
    'weight' =>  -10,
  ); 

  $items['admin/config/taxonomy_cleanup/capitalize'] = array(
    'title' => 'Capitalize Terms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxonomy_cleanup_capitalize_settings_form'),
    'access callback' => TRUE,
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_NORMAL_ITEM,
    'weight' =>  -10,
  ); 

  $items['admin/config/taxonomy_cleanup/split'] = array(
    'title' => 'Split Terms',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('taxonomy_cleanup_split_settings_form'),
    'access callback' => TRUE,
    'access arguments' => array('administer taxonomy'),
    'type' => MENU_NORMAL_ITEM,
    'weight' =>  -10,
  ); 

  return $items;
}

function taxonomy_cleanup_edit_form($form, &$form_state, array $rule = array()) {

  $form['taxonomy_cleanup'] = array(
    '#markup' => '
    <p>You can clean up the Categories Taxonomy in two ways.</p>
    <h4>Categories</h4>
    Vocabulary of free tags.
    <ul>
      <li><a href="/admin/config/taxonomy_cleanup/remove_empty_terms/4">Remove Empty Terms: Categories</a></li>
      <li><a href="/admin/config/taxonomy_cleanup/merge_similar_terms/4">Merge Similar Terms: Categories</a></li>
      <li><a href="/admin/config/taxonomy_cleanup/capitalize/4">Capitalize Terms: Categories</a></li>
      <li><a href="/admin/config/taxonomy_cleanup/split/4">Split Terms: Categories</a></li>
    </ul>

    <h4>Neighborhoods</h4>
    <ul>
      <li><a href="/admin/config/taxonomy_cleanup/merge_similar_terms/10">Merge Similar Terms: Neighborhoods</a></li>
      <li><a href="/admin/config/taxonomy_cleanup/capitalize/10">Capitalize Terms: Neighborhoods</a></li>
      <li><a href="/admin/config/taxonomy_cleanup/split/10">Split Terms: Neighborhoods</a></li>
      <li>Coming soon: preload neighborhoods</li>
    </ul>

    <ul>
      <li>Coming one day: Preload Civic Taxonomy from Citygories</li>
      <li><a href="/admin/structure/taxonomy/categories/add">Add term to category vocabulary</a></li>
    </ul>
    ',
  );

  return system_settings_form($form);
}

function taxonomy_cleanup_remove_empty_terms($vid) {
  $terms = taxonomy_cleanup_get_term_from_vid($vid);
  
  foreach ($terms as $tid => $term) {
    $nodes = taxonomy_select_nodes($tid);
    if(empty($nodes)) {
      drupal_set_message("Removing Empty Term: " . $term);   
      taxonomy_term_delete($tid);
    }
  }

  drupal_set_message("All empty terms removed");
  return "";
}


function taxonomy_cleanup_split_settings_form() {
  $output = '';

  $args = func_get_args();

  // Remove $form_id from the arguments.
  array_shift($args);
  $form_state['build_info']['args'] = $args;
  $vid = $args[1];

  $terms = taxonomy_cleanup_get_term_from_vid($vid);

  global $base_url;

  foreach ($terms as $tid => $term) {
    $link_tid = $base_url . '/taxonomy/term/' . $tid;
    $output .= "<p><strong>" . l($term, $link_tid) . "</strong></p>";
  }

  $form = array();

  $form['taxonomy_cleanup'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Capitalize a term'), 
    '#collapsible' => FALSE, 
    '#collapsed' => FALSE,
    '#suffix' => $output,
  );

  $form['taxonomy_cleanup']['split_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Term to split'),
    '#description' => t("Enter a term to split"),
  );

  $form['taxonomy_cleanup']['split_term_dest_1'] = array(
    '#type' => 'textfield',
    '#title' => t('New tag 1'),
    '#description' => t("Enter a new term"),
  );

  $form['taxonomy_cleanup']['split_term_dest_2'] = array(
    '#type' => 'textfield',
    '#title' => t('New tag 2'),
    '#description' => t("Enter a new term"),
  );
  
  $form['taxonomy_cleanup']['split_term_dest_3'] = array(
    '#type' => 'textfield',
    '#title' => t('New tag 3'),
    '#description' => t("Enter a new term"),
  );  
   
  $form['taxonomy_cleanup']['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Split'),
  );
  
  $form['taxonomy_cleanup']['vid'] = array(
    '#type' => 'hidden',
    '#value' => $vid,
  );

  return $form;

}
/**
 * Submit function for term merging.
 */
function taxonomy_cleanup_split_settings_form_submit($form, $form_state, $vid) {
  $term = taxonomy_get_term_by_name($form_state['values']['split_term']);
  
  $vid = $form['taxonomy_cleanup']['vid']['#value'];
  
  $vocabulary = taxonomy_vocabulary_load($vid);

  $term = array_values($term);

  $new_terms = array();
  if(!empty($form_state['values']['split_term_dest_1'])) {
    $new_terms[] = $form_state['values']['split_term_dest_1'];
  }
  if(!empty($form_state['values']['split_term_dest_2'])) {
    $new_terms[] = $form_state['values']['split_term_dest_2'];
  }
  if(!empty($form_state['values']['split_term_dest_3'])) {
    $new_terms[] = $form_state['values']['split_term_dest_3'];  
  }
  
  $terms_to_merge = array();

  foreach($new_terms as $key) {
    // If term already exists.
    if($term_object = taxonomy_get_term_by_name($key)){
      $term_object = array_values($term_object);  
      $terms_to_merge[$term_object[0]->tid] = $term_object[0]->tid;
    }
    else {
      // Build a term object and assign it to the categories vocabulary.    

      $term_object_create = array(
        'name' => t($key),
        'vid' => $vid,
        'description' => '', 
        'parent' => array(0), 
        'vocabulary_machine_name' => $vocabulary->machine_name,    
      );

      $term_object_create = (object) $term_object_create;
      $new_term_object = taxonomy_term_save($term_object_create);
      $term_object = taxonomy_get_term_by_name($key);
      if($term_object) {
        $term_object = array_values($term_object); 
        $terms_to_merge[$term_object[0]->tid] = $term_object[0]->tid;
      }
    }
  }
  term_merge($term[0]->tid, $terms_to_merge, FALSE);
}

function taxonomy_cleanup_capitalize_settings_form() {
  $output = '';

  $args = func_get_args();

  // Remove $form_id from the arguments.
  array_shift($args);
  $form_state['build_info']['args'] = $args;
  $vid = $args[1];
  $terms = taxonomy_cleanup_get_term_from_vid($vid);

  global $base_url;

  foreach ($terms as $tid => $term) {
    $link_tid = $base_url . '/taxonomy/term/' . $tid;
    if (preg_match("/^[a-z]/", $term) == TRUE) { 
      $output .= "<p><strong>" . l($term, $link_tid) . "</strong></p>";
    }
    else {
      $output .= "<p>" . l($term, $link_tid) . "</p>";    
    }
  }

  $form = array();

  $form['taxonomy_cleanup'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Capitalize a term'), 
    '#collapsible' => FALSE, 
    '#collapsed' => FALSE,
    '#suffix' => $output,
  );

  $form['taxonomy_cleanup']['capitalize_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Term to capitalize'),
    '#description' => t("Enter a unique term name"),
  );

  $form['taxonomy_cleanup']['capitalize_all_terms'] = array(
    '#type' => 'checkbox',
    '#title' => t('Capitalize All'),
    '#description' => t("Capitalize all terms. (Cannot be undone.)"),
  );
   
  $form['taxonomy_cleanup']['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Capitalize'),
  );
  
  $form['taxonomy_cleanup']['vid'] = array(
    '#type' => 'hidden',
    '#value' => $vid,
  );

  return $form;
}

/**
 * Submit function for term merging.
 */
function taxonomy_cleanup_capitalize_settings_form_submit($form, $form_state) {
  if($form_state['values']['capitalize_all_terms'] == 1) {
    $output = '';
    $vid = $form['taxonomy_cleanup']['vid']['#value'];
    $terms = taxonomy_cleanup_get_term_from_vid($vid);
    $count = 0;
    global $base_url;

    foreach ($terms as $tid => $term) {
      $link_tid = $base_url . '/taxonomy/term/' . $tid; 
      if (preg_match("/^[a-z]/", $term) == TRUE) {      
        $term = taxonomy_term_load($tid);

        $term->name = ucfirst($term->name);  
        taxonomy_term_save($term);
        $count++;
      }
    }
    drupal_set_message($count . " terms capitalized.");
  }
  else {
    $term = taxonomy_get_term_by_name($form_state['values']['capitalize_term']);
    $term = array_values($term);
    $term[0]->name = ucfirst($term[0]->name);  
    taxonomy_term_save($term[0]);
    drupal_set_message($term[0]->name . " capitalized.");
  }
}


function taxonomy_cleanup_merge_similar_terms_settings_form() {
  $output = '';

  $args = func_get_args();

  // Remove $form_id from the arguments.
  array_shift($args);
  $form_state['build_info']['args'] = $args;
  $vid = $args[1];
  $terms = taxonomy_cleanup_get_term_from_vid($vid);

  global $base_url;

  foreach ($terms as $tid => $term) {
    $link_tid = $base_url . '/taxonomy/term/' . $tid;
    // @TODO Make work with autocomplete.
    // @TODO Ajax auto select items to merge.
    foreach($terms as $tid_sub => $term_sub) {
      if ((preg_match("/" . $term . "/i", $term_sub)) && ($term !== $term_sub)) {
        $link_tid_sub = $base_url. '/taxonomy/term/' . $tid_sub;
        $output .= "<p>Similar terms: <strong>" . l($term, $link_tid) . "</strong> & <strong>" . l($term_sub, $link_tid_sub) . '</strong></p>';     
      }
    }
  }
  
  $vocabulary = taxonomy_vocabulary_load($vid);

  if (!module_exists('term_merge') || !user_access('merge terms')) {
    return t('Term Merge module needs to be installed & enabled.');
  }
  
  $form = array();

  $form['taxonomy_cleanup'] = array(
    '#type' => 'fieldset', 
    '#title' => t('Terms to Merge'), 
    '#collapsible' => FALSE, 
    '#collapsed' => FALSE,
    '#suffix' => $output,
  );

  $form['taxonomy_cleanup']['dest_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Term to keep (destination)'),
    '#description' => t("Enter a unique term name"),
  );

  $form['taxonomy_cleanup']['source_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Term to remove (source)'),
    '#description' => t("Enter a unique term name"),
  );
   
  $form['taxonomy_cleanup']['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Merge'),
  );
  
  $form['taxonomy_cleanup']['vid'] = array(
    '#type' => 'hidden',
    '#value' => $vid,
  );

  return $form;
}

/**
 * Validate function for term merging.
 * @TODO fix this and/or use autocomplete on the taxonomy selection forms.
 */
/*
function taxonomy_cleanup_merge_similar_terms_settings_form_validate($form, $form_state) {

}
*/

/**
 * Submit function for term merging.
 */
function taxonomy_cleanup_merge_similar_terms_settings_form_submit($form, $form_state) {
  $selected_tids = array();
  $vid = $form['taxonomy_cleanup']['vid']['#value'];
  $terms = taxonomy_cleanup_get_term_from_vid($vid);
  
  $term_names_array = array_values($terms);

  if (module_exists('term_merge')) {
    $dest = array_values(taxonomy_get_term_by_name($form_state['values']['dest_term']));
    $source = array_values(taxonomy_get_term_by_name($form_state['values']['source_term']));

    foreach($dest as $key => $dest_value) {
      if(($dest_value->vid == $vid)) {

        if ($source[0]->vid == $vid){
          term_merge($source[0]->tid, $dest_value->tid, FALSE);
          drupal_set_message(t("Term %term_names merged into %dest_term. ", array('%term_names' => $source[0]->name, '%dest_term' => $dest_value->name)));
        }
      }
    }
  }
  else {
    drupal_set_message(t('Term merge module not found'));
  }
}

function taxonomy_cleanup_get_term_from_vid($vid) {
  $query = db_select('taxonomy_term_data', 't');
  $query->join('taxonomy_term_hierarchy', 'h', 'h.tid = t.tid');
  $query->fields('t', array('tid', 'name'));
  $query->condition('t.vid', $vid, '=');
  $query->condition('h.parent', 0, '='); // remove this line to get all terms.
  $result = $query->execute();

  while ($record = $result->fetchAssoc()) {
      $data[$record['tid']] = t($record['name']);
  }

  return $data;
}
