<?php

/**
 * Stats for CityGroups
 */
 
/**
 * Implementation of hook_cron().
 */
function citygroups_stats_cron() {
  citygroups_stats_build();
}

function citygroups_stats_menu() {
  $items['admin/citygroups_stats'] = array(
    'title' => 'CityGroups Stats',
    'page callback' => 'citygroups_stats_build_page',
    'access arguments' => array('access content'),
    'weight' => 1,
  );
  
  return $items;
}

function citygroups_stats_build_page() {
  citygroups_stats_build();
  $count =  variable_get('citygroups_stats_groups_published');
  return 'Groups counted:' . $count;
}

function citygroups_stats_build() {

  // Count number of published community groups.
  
  $result = db_query("SELECT nid, title FROM {node} WHERE type = :type AND status = :status", array(
    ':type' => 'community_group',
    ':status' => 1,
  ));

  $count_groups_published = $result->rowCount(); //Count the results.

  variable_set('citygroups_stats_groups_published', $count_groups_published);
  drupal_set_message(t('Number of Community Groups in the Directory: ') . $count_groups_published);
}
