<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function citygroups_content_help($path, $arg) {
  switch ($path) {
    case 'citygroups_content_collection':
      $explanation = t(
        'Custom content for CityGroups site.');
      return "<p>$explanation</p>";
  }
}

function citygroups_content_menu() {
  $items['map'] = array(
    'title' => 'Map',
    'page callback' => 'citygroups_content_map_render',
    'page arguments' => array(t('Render Map Page.')),
    'access callback' => TRUE,
  );
  return $items;
}

function citygroups_content_map_render() {
  return citygroups_group_map_render();
}

function citygroups_content_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module', 'citygroups_content') . '/js/stylish-select/jquery.stylish-select.min.js', array('type' => 'file',  'group' => JS_THEME, 'scope' =>'footer'));
}

include('citygroups_content.blocks.inc.php');