<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function citygroups_group_categories_help($path, $arg) {
  switch ($path) {
    case 'citygroups_group_categories':
      $explanation = t(
        'Custom features for Data Wiki Group Map.');
      return "<p>$explanation</p>";
  }
}


/**
 * Implementatation of hook_menu().
 */
function citygroups_group_categories_menu() {
  $items['categories'] = array(
    'title' => 'Map',
    'description' => 'Display a map of Community Groups.',
    'page callback' => '_citygroups_group_categories_render',
    'page arguments' => array(t('This page is displayed by the simplest (and base) menu example. Note that the title of the page is the same as the link title. You can also <a href="!link">visit a similar page with no menu link</a>', array('!link' => url('menu_example/path_only')))),
    'access callback' => TRUE,
    // 'file' => 'menu_example.module',

    // We can choose which menu gets the link. The default is 'navigation'.
    // 'menu_name' => 'navigation',

    // Show the menu link as expanded.
    'expanded' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_cron_job_scheduler_info().
 *
 * Compare queue names with key names in feeds_cron_queue_info().
 */
function citygroups_group_categories_cron_job_scheduler_info() {
  $info = array();
  $info['citygroups_group_categories_import'] = array(
    'queue name' => 'citygroups_group_categories_import',
  );
  return $info;
}

/**
 * Implements hook_cron_queue_info().
 */
function citygroups_group_categories_cron_queue_info() {
  $queues = array();
  $queues['citygroups_group_categories_import'] = array(
    'worker callback' => 'citygroups_group_categories_import',
    'time' => 15,
  );
  return $queues;
}

/**
 * Scheduler callback for importing from a source.
 */
function citygroups_group_categories_import($job) {

dsm("saving json");
}


function _citygroups_group_categories_render() {
  include('includes/group_categories.html.inc.php');
}

 
