<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function sea_blockwatch_help($path, $arg) {
  switch ($path) {
    case 'sea_blockwatch':
      $explanation = t(
        'Custom features for Seattle Blockwatch Finder.');
      return "<p>$explanation</p>";
  }
}
function sea_blockwatch_menu() {
  $items['blockwatch'] = array(
    'title' => 'Home',
    'page callback' => 'sea_blockwatch_home_render',
    'page arguments' => array(t('Blockwatch Home Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/map'] = array(
    'title' => 'Map',
    'page callback' => 'sea_blockwatch_map_render',
    'page arguments' => array(t('Blockwatch Map Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/list'] = array(
    'title' => 'List',
    'page callback' => 'sea_blockwatch_list_render',
    'page arguments' => array(t('Blockwatch List Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/topics'] = array(
    'title' => 'Topics',
    'page callback' => 'sea_blockwatch_topics_render',
    'page arguments' => array(t('Blockwatch Topics Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/about'] = array(
    'title' => 'About',
    'page callback' => 'sea_blockwatch_about_render',
    'page arguments' => array(t('Blockwatch About Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/add'] = array(
    'title' => 'Add',
    'page callback' => 'sea_blockwatch_add_render',
    'page arguments' => array(t('Blockwatch Add Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'sea_blockwatch_contact_render',
    'page arguments' => array(t('Blockwatch Contact Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/upload'] = array(
    'title' => 'Upload',
    'page callback' => 'sea_blockwatch_upload_render',
    'page arguments' => array(t('Blockwatch Upload Page')),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_home_render() {
  $output = "";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_map_render() {
  $output = "map";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_list_render() {
  $output = "list";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_topics_render() {
  $output = "topics";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_about_render() {
  $output = "about";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_add_render() {
  $output = "add";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_upload_render() {
  $output = "upload";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_contact_render() {
  $output = "contact";
  return $output;
}

/**
 * Create variables for theme.
 */
function sea_blockwatch_preprocess_page(&$vars) {
  $vars['page_path'] = isset($_GET['q']) ? $_GET['q'] : '<front>';
  
  switch ($vars['page_path']) {
    case 'blockwatch/list':
    case 'blockwatch/add': 
    case 'blockwatch/about':
    case 'blockwatch/contact':
    case 'blockwatch/topics':
    case 'blockwatch/upload':
      sea_blockwatch_page_variables($vars);
      break;
    case 'blockwatch':
    case 'blockwatch/map':  
      sea_blockwatch_page_variables($vars);
      datawiki_group_map_page_variables($vars);
    break;
  }
}
function sea_blockwatch_map_render_output() {
  $output = '<div>
    <div id="map" style="width: 600px; height: 400px"><div class="loading">Loading Map</div></div>
    <div id="data"></div>
  </div>

  <div id="popup-content" class="block">
      <div class="content">Click map to see where the groups are</div>
  </div>';
  return $output;
}

/** 
 * Generate settings and return them to the theme.
 */
function sea_blockwatch_page_variables(&$vars) {
  // Override existing page variables.
  $vars['site_slogan'] = "A public directory of block watch captains in Seattle.";
  $vars['logo_image_link'] = drupal_get_path('module', 'sea_blockwatch') . '/images/citygroups-logo.png';
  $vars['logo'] = '<a href="/"><img src="/' . $vars['logo_image_link'] . '" /></a>';

  // Custom object of special settings to be integrated with the main theme.
  $vars['section'] = array();
  $vars['section']['html_root'] = drupal_get_path('module', 'datawiki_group_map');
  $vars['section']['html_root_custom'] = drupal_get_path('module', 'sea_blockwatch');
  // Get current theme
  // Set these settings in the theme or the submodule (ex. sea_blockwatch.)
  $vars['section']['page_title'] = t('CityGroups Map');
  $vars['section']['section_name'] = "Block Watch Captain Finder";
  $vars['section']['place'] = "Seattle";
  $vars['section']['theme'] = "citygroups_blockwatch";
  $vars['section']['term'] = "block-watch";
/*
  $vars['section']['popular_searches'] = '<ul>
            <li><a href="#defaultPath">See All</a></li>
            <li><a href="#block-watch">Block Watch</a></li>
            <li><a href="#public-safety">Public Safety</a></li>
          </ul><br />
          <a href="/categories">All Categories</a>';
*/
        
  $vars['section']['javascript_settings'] = array(); 
  $vars['section']['javascript_settings'] = array(); 
  $vars['section']['javascript_settings']['mapColors'] = array();
  $vars['section']['javascript_settings']['mapColors']['color'] = "#2796F2";
  $vars['section']['javascript_settings']['mapColors']['fillColor'] = "#FFFFFF";
  $vars['section']['javascript_settings']['mapColors']['fillOpacity'] = 0.5;
  $vars['section']['javascript_settings']['mapColors']['weight'] = 1;
  $vars['section']['javascript_settings']['mapColors']['opacity'] = 1;
    
/*
  $vars['section']['javascript_settings']['mapMarkerStyle'] = '{
        iconUrl: "/' . $vars['section']['html_root_custom'] . '/includes/images/placeholder_marker.png",
        iconSize: new L.Point(15, 40),
        iconAnchor: new L.Point(10, 40),
        popupAnchor: new L.Point(0, 0)
    }';
*/
  $vars['section']['javascript_settings']['mapMarkerIconUrl'] =  "/" . $vars['section']['html_root_custom'] . "/images/noun_project_659_man.svg";
  $vars['section']['javascript_settings']['mapMarkerIconPointSize'] = array(10,25);
  $vars['section']['javascript_settings']['mapMarkerIconAnchor'] = array(0,0);
  $vars['section']['javascript_settings']['mapMarkerPopupAnchor'] = array(0,0);
  // Add special stylesheet.
  drupal_add_css(drupal_get_path('module', 'sea_blockwatch') . '/css/blockwatch.css', array('group' => CSS_THEME));
}

include('sea_blockwatch.blocks.inc.php');