<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function sea_blockwatch_help($path, $arg) {
  switch ($path) {
    case 'sea_blockwatch':
      $explanation = t(
        'Custom features for Seattle Blockwatch Finder.');
      return "<p>$explanation</p>";
  }
}

function sea_blockwatch_menu() {
  $items['blockwatch'] = array(
    'title' => 'Home',
    'page callback' => 'sea_blockwatch_home_render',
    'page arguments' => array(t('Blockwatch Home Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/map'] = array(
    'title' => 'Map',
    'page callback' => 'sea_blockwatch_map_render',
    'page arguments' => array(t('Blockwatch Map Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/topics'] = array(
    'title' => 'Topics',
    'page callback' => 'sea_blockwatch_topics_render',
    'page arguments' => array(t('Blockwatch Topics Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/about'] = array(
    'title' => 'About',
    'page callback' => 'sea_blockwatch_about_render',
    'page arguments' => array(t('Blockwatch About Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/add'] = array(
    'title' => 'Add',
    'page callback' => 'sea_blockwatch_add_render',
    'page arguments' => array(t('Blockwatch Add Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'sea_blockwatch_contact_render',
    'page arguments' => array(t('Blockwatch Contact Page')),
    'access callback' => TRUE,
  );
  $items['blockwatch/upload'] = array(
    'title' => 'Upload',
    'page callback' => 'sea_blockwatch_upload_render',
    'page arguments' => array(t('Blockwatch Upload Page')),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_home_render() {
  $output = "";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_map_render() {
  $output = "";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_list_render() {
  $output = "";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_topics_render() {
  $output = "";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_about_render() {
  $output = "";
  return $output;
}
/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_add_render() {
  $output = "";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_upload_render() {
  $output = "";
  return $output;
}

/**
 * Render custom page for blockwatch.
 */
function sea_blockwatch_contact_render() {
  $output = "";
  return $output;
}

/**
 * Create variables for theme.
 */
function sea_blockwatch_preprocess_page(&$vars) {
  $vars['page_path'] = isset($_GET['q']) ? $_GET['q'] : '<front>';
  
  switch ($vars['page_path']) {
    case 'blockwatch/add': 
    case 'blockwatch/about':
    case 'blockwatch/contact':
    case 'blockwatch/topics':
    case 'blockwatch/upload':
    case 'list/all/block-watch':
      sea_blockwatch_page_variables($vars);
      break;
    case 'node/add/community-group':
      if(!empty($_GET['section'])) {
        $section = $_GET['section'];
        if($section == 'blockwatch') {
          sea_blockwatch_page_variables($vars);
          $vars['title'] = t('Add Block Watch Group');
        }
      }
      break;
    case 'blockwatch':
    case 'blockwatch/map':
      sea_blockwatch_page_variables($vars);
      datawiki_group_map_page_variables($vars);
    break;
  }
}
function sea_blockwatch_map_render_output() {
  $output = '<div>
    <div id="map" style="width: 600px; height: 400px"><div class="loading">Loading Map</div></div>
    <div id="data"></div>
  </div>

  <div id="popup-content" class="block">
      <div class="content">Click map to see where the groups are</div>
  </div>';
  return $output;
}

/**
 * Alter the community group form (a content type.)
 */
function sea_blockwatch_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'community_group_node_form') {
  
    global $section;
    $section = 'blockwatch';
  
    $menu =  menu_tree('menu-block-watch-menu');
    $menu_rendered = drupal_render($menu);

    $form['#prefix'] .= '<div class="add-home-menu">' . $menu_rendered . '</div>';
  
    // Section overrides.
    $add_variables_array = array(
      'category' => 'Block Watch, Crime Prevention',
      'title' => 'Add a Block Watch Captain',
      'instructions' => 'List Block Watch Captain or Block Watch Group.',
      'map_instructions' => 'Where is this Block Watch?',
    );
    
    if(!empty($add_variables_array['instructions'])) {
      $form['#prefix'] .= '<h3>' .  $add_variables_array['instructions'] . '</h3>';
    }
    
    if(!empty($add_variables_array['category'])) {
      $form['field_categories']["und"]["#default_value"] = $add_variables_array['category'];
    }

    if(!empty($add_variables_array['map_instructions'])) {
      $form['#groups']['group_geographic']->label = $add_variables_array['map_instructions'];
    }
    
    $access = user_access('administer nodes');
    if(!$access) {
      $form['additional_settings']['#access'] = FALSE;
    }

    $form['field_location']['#prefix'] = '<div id="field-location-add-more-wrapper">';
    $form['field_location']['#prefix'] .= '<div class="map-instructions-container">';
    $form['field_location']['#prefix'] .= '<div class="instructions-1">';
    $form['field_location']['#prefix'] .= t('Enter address or intersection to map the group.');
    $form['field_location']['#prefix'] .= '</div>';
    $form['field_location']['#prefix'] .= '<div class="instructions-2">';
    $form['field_location']['#prefix'] .= t('Draw the shape of the extent of this group.');
    $form['field_location']['#prefix'] .= '</div>';
    $form['field_location']['#prefix'] .= '<div class="address-ajax">';
    $form['field_location']['#prefix'] .= '<div id="search-links">';
    $form['field_location']['#prefix'] .= '<div id="search-places" class="form-input">';
    $form['field_location']['#prefix'] .= '<input placeholder="Enter address or zipcode." size=50 class="form-item" id="search-map-input" />';
    $form['field_location']['#prefix'] .= '<input type="image" src="' . base_path() . path_to_theme() . '/images/search_icon-50.png" id="search-links-submit" class="search_btn" value="Search" alt="Search">';
    $form['field_location']['#prefix'] .= '</div>';
    $form['field_location']['#prefix'] .= '</div><div class="clear"></div>';   
    $form['field_location']['#prefix'] .= '</div>';

    // Add Google API (uses openlayers API key)
    // @TODO require openlayers.
    drupal_add_js(
        'http://maps.google.com/maps/api/js?sensor=false&key=' . 
        variable_get('openlayers_layers_google_api', 
          variable_get('googlemap_api_key', '')
        ), 'external');

    drupal_add_js(drupal_get_path('module', 'community_group_form') . '/js/community_group_form.js', array('type' => 'file',  'group' => JS_THEME, 'scope' =>'footer'));          
  }
}

/** 
 * Generate settings and return them to the theme.
 */
/** 
 * Generate settings and return them to the theme.
 */
function sea_blockwatch_page_variables(&$vars) {
  if(empty($vars['section'])) {
    $settings = sea_blockwatch_settings($vars);
  }
  else {
    $settings = $vars['section'];
  }

  // Override existing page variables.
/*   $vars['site_slogan'] = '<h3>' .t("Public directory of Seattle Block Watch Captains.") . '</h3>'; */
/*   $vars['logo_image_link'] = drupal_get_path('module', 'sea_blockwatch') . '/images/citygroups-logo.png'; */
/*   $vars['logo'] = '<a href="/"><img src="/' . $vars['logo_image_link'] . '" /></a>'; */

  // Custom object of special settings to be integrated with the main theme.
  $vars['section'] = array();
  $vars['section']['html_root'] = drupal_get_path('module', 'datawiki_group_map');
  $vars['section']['html_root_custom'] = drupal_get_path('module', 'sea_blockwatch');
  // Get current theme
  // Set these settings in the theme or the submodule (ex. sea_blockwatch.)
  $vars['section']['page_title'] = t('Map');
  $vars['section']['section_name'] = "Block Watch Captain Directory";
  $vars['section']['place'] = "Seattle";
  $vars['section']['theme'] = "citygroups_blockwatch";
  $vars['section']['term'] = "Block-watch";
  $vars['section']['javascript_settings'] = $settings['javascript_settings'];

  // Add javascript.

  // Add Google API (uses openlayers API key)
  // @TODO require openlayers.
  drupal_add_js(
      'http://maps.google.com/maps/api/js?sensor=false&key=' . 
      variable_get('openlayers_layers_google_api', 
        variable_get('googlemap_api_key', '')
      ), 'external');

  // Pass javascript settings into container variable.
  $datawiki_js_settings = array();
  $datawiki_js_settings['datawiki'] = $settings['javascript_settings'];
  drupal_add_js($datawiki_js_settings, 'setting');
  
  // Add special stylesheet.
  drupal_add_css(drupal_get_path('module', 'sea_blockwatch') . '/css/blockwatch.css', array('group' => CSS_THEME));
}

/**
 * Generate settings that will be used in javascript.
 * Can be overriden in submodules.
 */
function sea_blockwatch_settings() {
  global $section;
  $section = 'blockwatch';

  $settings = array();
  $settings['html_root'] = drupal_get_path('module', 'datawiki_group_map');
  $settings['html_root_custom'] = drupal_get_path('module', 'sea_blockwatch');
  // Get current theme
  // Set these settings in the theme or the submodule (ex. sea_blockwatch.)
  // Set the theme.  
  $settings['theme'] = "datawiki";
  $settings['term'] = "all";         
  $settings['javascript_settings'] = array();
  $settings['javascript_settings']['customMapDataPath'] = 'data/community-group/map/Block-watch';
  $settings['javascript_settings']['mapColors'] = array();
  $settings['javascript_settings']['mapColors']['color'] = "#2796F2";
  $settings['javascript_settings']['mapColors']['fillColor'] = "#FFFFFF";
  $settings['javascript_settings']['mapColors']['fillOpacity'] = 0.5;
  $settings['javascript_settings']['mapColors']['weight'] = 1;
  $settings['javascript_settings']['mapColors']['opacity'] = 1;
  $settings['javascript_settings']['mapMarkerIconUrl'] =  "/" . $settings['html_root_custom'] . "/images/map-marker.png";
  $settings['javascript_settings']['mapMarkerIconShadowUrl'] =  "";
  $settings['javascript_settings']['mapMarkerIconPointSize'] = array(10,20);
  $settings['javascript_settings']['mapMarkerIconShadowSize'] = array(10,20);
  $settings['javascript_settings']['mapMarkerIconAnchor'] = array(0,0);
  $settings['javascript_settings']['mapMarkerPopupAnchor'] = array(0,0);
  return $settings;
}

include('sea_blockwatch.blocks.inc.php');