<?php 

/* 
 Implementation of vocabulary loading hook.
 @TODO This is only really sort of a hook.
*/ 
function citygroups_vocabulary_build_vocabulary_neighborhood(&$vocabulary) {
  $vocabulary_name = 'neighborhood';
  $terms = array(
'Alamo Square',
'Anza Vista',
'Ashbury Heights',
'Balboa Park',
'Balboa Terrace',
'Bayview',
'Bernal Heights',
'Buena Vista',
'Castro',
'Cathedral Hill',
'Cayuga Terrace',
'China Basin',
'China Heights',
'Civic Center',
'Clarendon Heights',
'Cole Valley',
'Corona Heights',
'Cow Hollow',
'Crocker-Amazon',
'Design District',
'Diamond Heights',
'Dogpatch',
'Dolores Heights',
'Duboce Triangle',
'Embarcadero',
'Eureka Valley',
'Excelsior',
'Fillmore',
'Financial District',
'Financial District South',
'Fisherman\'s Wharf',
'Forest Hill',
'Forest Knolls',
'Frederick Knob',
'French Quarter (Belden Place)',
'Glen Park',
'Golden Gate Heights',
'Haight-Ashbury',
'Hayes Valley',
'Hunters Point',
'India Basin',
'Ingleside',
'Ingleside Terraces',
'Inner Sunset',
'Islais Creek',
'Jackson Square',
'Japantown',
'Jordan Park',
'Laguna Honda',
'Lake',
'Lakeside',
'Lakeshore',
'Laurel Heights',
'Little Hollywood',
'Little Russia',
'Little Saigon',
'Lone Mountain',
'Lower Haight',
'Lower Pacific Heights',
'Lower Nob Hill',
'Marina District',
'Merced Heights',
'Merced Manor',
'Midtown Terrace',
'Miraloma Park',
'Mission Bay',
'Mission District',
'Mission Dolores',
'Mission Terrace',
'Monterey Heights',
'Mount Davidson',
'Nob Hill',
'Noe Valley',
'North Beach',
'Oceanview',
'Outer Mission',
'Pacific Heights',
'Panhandle',
'Parkmerced',
'Parkside',
'Polk Gulch',
'Portola',
'Portola Place',
'Potrero Hill',
'Presidio',
'Presidio Heights',
'Richmond District',
'Rincon Hill',
'Russian Hill',
'Saint Francis Wood',
'Sea Cliff',
'Sherwood Forest',
'Silver Terrace',
'Somisspo',
'South Beach',
'South of Market',
'South Park',
'Sunnydale',
'Sunnyside',
'Sunset District',
'Telegraph Hill',
'Tenderloin',
'Treasure Island',
'Twin Peaks',
'Union Square',
'University Mound',
'Upper Market',
'Visitacion Valley',
'Vista del Mar',
'West Portal',
'Western Addition',
'Westwood Highlands',
'Westwood Park',
'Yerba Buena'
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}




function citygroups_vocabulary_build_vocabulary_zipcode(&$vocabulary) {
  $vocabulary_name = 'zipcode';
  $terms = array(
/*     'Term', */
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}

function citygroups_vocabulary_build_vocabulary_state(&$vocabulary) {
  $vocabulary_name = 'state';
  $terms = array(
    'CA',
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}


function citygroups_vocabulary_build_vocabulary_county(&$vocabulary) {
  $vocabulary_name = 'county';
  $terms = array(
'Alameda County',
'Contra Costa County',
'Marin County',
'Napa County',
'San Francisco County',
'San Mateo County',
'Santa Clara County',
'Solano County',
'Sonoma County'
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}

function citygroups_vocabulary_build_vocabulary_demographics(&$vocabulary) {
  // This is a list of terms output from various systems.
  // Should provide list of cultural & personal statuses.
  // The idea is to have a big list of everything necessary for your city.
  
  $vocabulary_name = 'categories';
  
  $terms = array(
    'African',
    'African American',
    'Arab',
    'Asian',
    'Asian Pacific Islander',
    'Cambodian',
    'Caucasian',
    'Chinese',
    'East African',
    'Eastern European',
    'Eritrean',
    'Ethiopian',
    'Filipino',
    'First Nations',
    'Hmong',
    'Interracial',
    'Iraqi',
    'Japanese',
    'Jewish',
    'Khmer',
    'Korean',
    'Latino',
    'Muslim',
    'Native American',
    'Nepali',
    'Nordic',
    'Norwegian',
    'People of color',
    'Queer',
    'Samoan',
    'Somali',
    'Sudanese',
    'Taiwanese',
    'Transgender',
    'Turkish',
    'Vietnamese',
    
    'Homeowner',
    'Renter',
    'Homeless',
    'Parent',
    'Dependent',
    'Volunteer',
    'Neighbor',
    'Citizen',
    'Immigrant/Refugee',
    'Immigrant',
    'Refugee',
    'Samaritan',
    'Children',
    'Dads',
    'Divorced Families',
    'Family',
    'Moms',
    'Parents',    
    'Renters',   
    'Singles',    
    'Youth',
    'Seniors',
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}


function citygroups_vocabulary_build_vocabulary_city(&$vocabulary) {
  $vocabulary_name = 'city';
  $terms = array(
    'Seattle',
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}


function citygroups_vocabulary_build_vocabulary_area_code(&$vocabulary) {
  $vocabulary_name = 'area_code';
  $terms = array(
    '415',
    '510',
  );
  return citygroups_vocabulary_build_terms($terms, &$vocabulary);
}