<?php

/**
 * @file
 * 
 * This module just triggers loads CityGroups.
 */

/**
 * Implements hook_help().
 */
function citygroups_help($path, $arg) {
  switch ($path) {
    case 'citygroups_collection':
      $explanation = t(
        'Custom content for CityGroups site.');
      return "<p>$explanation</p>";
  }
}

function citygroups_form_alter(&$form, &$form_state, $form_id) {
  // drupal_add_js(drupal_get_path('module', 'citygroups') . '/js/stylish-select/jquery.stylish-select.min.js', array('type' => 'file',  'group' => JS_THEME, 'scope' =>'footer'));
}

/**
 * Menu items for CityGroups
 * 
 * These are connected to the main menus, but the content & forms 
 * are overwritten.
 */
function citygroups_menu() {
  $items['admin/config/citygroups'] = array(
    'title' => 'CityGroups Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('citygroups_edit_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 1,
    'file' => 'citygroups.admin.inc',
  );
  
  return $items;
}


function citygroups_promote() {
  $output = '<ul class="promote">';
  if(variable_get('citygroups_social_media_twitter')) {
    $output .= '<li>' . l('Twitter', 'http://twitter.com/' . variable_get('citygroups_social_media_twitter')) . '</li>';
  }
  if(variable_get('citygroups_social_media_facebook')) {
    $output .= '<li>' . l('Facebook', variable_get('citygroups_social_media_facebook')) . '</li>';
  }
  if(variable_get('citygroups_mailing_list')) {
    $output .= '<li>' . l('Mailing List', variable_get('citygroups_mailing_list')) . '</li>';
  }
  if(variable_get('citygroups_social_media_flyer')) {
    $output .= '<li>' . l('Flyer', variable_get('citygroups_social_media_flyer')) . '</li>';
  }
  $output .= '</ul>';
 
  return $output;
}

include('citygroups.blocks.inc.php');
