<?php

/**
 * @file
 * Custom module that renders and caches a json+leaflet map.
 */

/**
 * Implements hook_help().
 */
function citygroups_sub_help($path, $arg) {
  switch ($path) {
    case 'citygroups_sub_collection':
      $explanation = t(
        'Custom features for CityGroups site.');
      return "<p>$explanation</p>";
  }
}

function citygroups_sub_menu() {
  $items['map'] = array(
    'title' => 'CityGroups Map',
    'page callback' => 'citygroups_sub_map_render',
    'page arguments' => array(t('Render Map Page.')),
    'access callback' => TRUE,
  );
  $items['projects'] = array(
    'title' => 'CityGroups Data Collection Projects',
    'page callback' => 'citygroups_sub_projects_render',
    'page arguments' => array(t('Render Projects Page.')),
    'access callback' => TRUE,
  );
  return $items;
}

function citygroups_sub_map_render() {
  return datawiki_group_map_render();
}

function citygroups_sub_projects_render() {
  return t('These are some data collection projects we are doing.');
}

function citygroups_sub_set_theme() {

}

include('citygroups_sub.blocks.inc.php');